In [8]:
import torch

In [9]:
x = torch.ones(3,3,requires_grad=True)

In [10]:
x.requires_grad

True

In [11]:
y = x + 2

In [12]:
y

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward>)

In [13]:
y.requires_grad

True

In [14]:
y.grad_fn

In [15]:
z = y * y * 3

In [20]:
out = z.mean()

In [21]:
print(z)
print(out)

tensor([[27., 27., 27.],
        [27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward>)
tensor(27., grad_fn=<MeanBackward1>)


In [22]:
out.backward()

In [23]:
print(x.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
