In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[1.4700e+35, 4.5622e-41, 1.1135e+36],
        [3.0631e-41, 1.0487e+36, 3.0631e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.0790e+36]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.4077, 0.7878, 0.0151],
        [0.2101, 0.9052, 0.6776],
        [0.8108, 0.6820, 0.4946],
        [0.5239, 0.1794, 0.7146],
        [0.2973, 0.0246, 0.0109]])


In [4]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x.dtype

torch.float64

#### Operations

* Addition

In [8]:
x = torch.rand(5,3)
y = torch.rand(5,3)

In [9]:
print(x)

tensor([[0.8852, 0.9387, 0.1194],
        [0.0628, 0.0916, 0.3471],
        [0.0763, 0.5025, 0.6286],
        [0.5482, 0.0210, 0.0976],
        [0.4658, 0.2854, 0.6363]])


In [10]:
print(y)

tensor([[0.9718, 0.3357, 0.7331],
        [0.6471, 0.1612, 0.1757],
        [0.3888, 0.0604, 0.8841],
        [0.5809, 0.8774, 0.3835],
        [0.6796, 0.1103, 0.3682]])


In [11]:
print(x+y)

tensor([[1.8569, 1.2743, 0.8525],
        [0.7099, 0.2528, 0.5229],
        [0.4651, 0.5629, 1.5127],
        [1.1291, 0.8984, 0.4810],
        [1.1454, 0.3958, 1.0045]])


In [12]:
print(torch.add(x,y))

tensor([[1.8569, 1.2743, 0.8525],
        [0.7099, 0.2528, 0.5229],
        [0.4651, 0.5629, 1.5127],
        [1.1291, 0.8984, 0.4810],
        [1.1454, 0.3958, 1.0045]])


In [13]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.8569, 1.2743, 0.8525],
        [0.7099, 0.2528, 0.5229],
        [0.4651, 0.5629, 1.5127],
        [1.1291, 0.8984, 0.4810],
        [1.1454, 0.3958, 1.0045]])


In [14]:
y.add_(x)

tensor([[1.8569, 1.2743, 0.8525],
        [0.7099, 0.2528, 0.5229],
        [0.4651, 0.5629, 1.5127],
        [1.1291, 0.8984, 0.4810],
        [1.1454, 0.3958, 1.0045]])

In [15]:
print(y)

tensor([[1.8569, 1.2743, 0.8525],
        [0.7099, 0.2528, 0.5229],
        [0.4651, 0.5629, 1.5127],
        [1.1291, 0.8984, 0.4810],
        [1.1454, 0.3958, 1.0045]])


In [16]:
y[:,1]

tensor([1.2743, 0.2528, 0.5629, 0.8984, 0.3958])

* Resize

In [17]:
x.view(15)

tensor([0.8852, 0.9387, 0.1194, 0.0628, 0.0916, 0.3471, 0.0763, 0.5025, 0.6286,
        0.5482, 0.0210, 0.0976, 0.4658, 0.2854, 0.6363])

In [18]:
x = torch.rand(4,4)

In [19]:
print(x)

tensor([[0.0364, 0.3556, 0.7054, 0.2565],
        [0.7510, 0.3947, 0.3245, 0.1773],
        [0.6459, 0.5806, 0.1702, 0.8278],
        [0.1360, 0.3786, 0.9387, 0.5574]])


In [20]:
y = x.view(16)
print(y)

tensor([0.0364, 0.3556, 0.7054, 0.2565, 0.7510, 0.3947, 0.3245, 0.1773, 0.6459,
        0.5806, 0.1702, 0.8278, 0.1360, 0.3786, 0.9387, 0.5574])


In [21]:
print(y.size())

torch.Size([16])


In [22]:
z = x.view(-1,8)
print(z)

tensor([[0.0364, 0.3556, 0.7054, 0.2565, 0.7510, 0.3947, 0.3245, 0.1773],
        [0.6459, 0.5806, 0.1702, 0.8278, 0.1360, 0.3786, 0.9387, 0.5574]])


In [23]:
print(z.size())

torch.Size([2, 8])


#### Numpy Bridging

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

* Torch tensor to Numpy

In [24]:
a = torch.ones(10)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


* Numpy to Torch tensor

In [27]:
import numpy as np
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [28]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [29]:
np.add(a,1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)
